### ISSUE TITLE
about the Restormer result

### ISSUE THREAD

**Issue by chensming** [mdyao/NDR-Restore#1]
Hello, after reading your paper, I'm interested in your work. 
Also, I has a question on this table, restormer is single-tasking, so when using it to do multi-tasking, do you modify the code provided by the original author  or in your own reproduction of the framework to run the experiments with it?

<div align="center">
<img src="https://github.com/mdyao/NDR-Restore/assets/45591767/a213a878-dea3-40f9-80e4-a6ea60772a91" width="60%">
</div>

**Comment by mdyao** [comment]
Hi, thanks for your attention, we mix the datasets to train the restormer.
