### ISSUE TITLE
experiment results

### ISSUE THREAD

**Issue by boohit** [mdyao/NDR-Restore#3]
Thank you very much for your work. Regarding the experimental results, I have some questions: why do the results obtained using the pre trained model you provided differ from those in your paper? Thank you.

**Comment by boohit** [comment]
![捕获](https://github.com/user-attachments/assets/2e99cbaf-c693-4184-8300-4f209bc9b432)

**Comment by mdyao** [comment]
Hi, to align with previous all-in-one methods (e.g., AirNet, PromptIR), in this repo, we provide model parameters trained using the same dataset ratio, enabling easy comparison with those methods. Specifically, the denoising dataset was replicated 3 times, the deraining dataset was replicated 120 times, and the dehazing dataset remained unchanged. Please refer to [https://github.com/va1shn9v/PromptIR/blob/main/utils/dataset_utils.py](url).
