### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by hhhhhhalf** [mdyao/NDR-Restore#7]
Hello, I would like to ask you a few questions: How should we understand the benefits of NDR for the restoration network when training on a single task? Is it because the degradation learning process simultaneously optimizes the encoder to better learn the degradation patterns, thereby achieving improved results?

**Comment by mdyao** [comment]
Thank you for your interest in our work. We think the improvements in single-task performance stem from several factors, including adjustments to the backbone architecture, more refined training parameters, and better parameter optimization overall. However, regarding the impact of the bidirectional optimization strategy on single-task scenarios, we have not conducted specific validation experiments. We welcome further exploration in this area.

**Comment by hhhhhhalf** [comment]
Okay, I understand. Thank you for your reply!
